version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  fastapi:
    image: python:3.12
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    image: python:3.12
    command: /bin/bash -c "pip install --no-cache-dir -r requirements.txt && celery -A celery_worker worker --loglevel=info"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis